name: Run Lint, Test & Deploy on Push
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Get the Node jobs
        uses: actions/setup-node@v3
        with:
          version: 18
      - name: Install Dependencies
        run: npm ci            
      - name: Run the lint report
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Get the Node jobs
        uses: actions/setup-node@v3
        with:
          version: 18
      - name: Install Dependencies
        run: npm ci          
      - name: Run the test report
        run: npm test  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Get the Node jobs
        uses: actions/setup-node@v3
        with:
          version: 18
      - name: Install Dependencies
        run: npm ci          
      - name: Build the project
        run: npm run build
      - name: Run the deploy
        run: echo "deploying..."